#ifndef WHROV_HMI_CONSTANTS_H_
#define WHROV_HMI_CONSTANTS_H_

namespace whrov_hmi {
enum ORDER_TYPE { HEADING = 0, HOLD, UPDATE_IMG_SETTINGS, HOLD_POSITION, HOLD_POSITION_STOP, GOTO, GOTO_STOP};
}

#endif
